language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -r SigmaPi/requirements.txt
script:
  - cd SigmaPi/
  - python manage.py validate
  - python manage.py test
  - coverage run --source='.' manage.py test
  - coverage report
  - coveralls
after success:
  - coveralls
